name: Daily Repository Update

on:
  schedule:
    - cron: '0 8 * * *'  # Runs daily at 08:00 AM UTC
  workflow_dispatch:  # Allows manual trigger

jobs:
  daily-commit:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Configure Git - baruch.georgeponnumani@straive.com
      run: |
        git config --global user.name "GitHub Action Bot"
        git config --global user.email "baruch.georgeponnumani@straive.com"

    - name: Add and Commit Changes - baruch.georgeponnumani@straive.com
      run: |
        date >> daily_update.log
        git add daily_update.log
        git commit -m "Daily update $(date)" || echo "No changes to commit"

    - name: Push Changes - baruch.georgeponnumani@straive.com
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }} HEAD:main
